// Generated by CoffeeScript 1.6.3
(function() {
  var CharacterSheet, PRIMARY_MAPPING, SECONDARY_MAPPING, SHEET_MAPPING, SKILLS, ceil, floor, max, merge_objects, min, object_keep, varnamize,
    __slice = [].slice;

  SKILLS = {
    acting: {
      5: 2,
      10: 5
    },
    artisan: {
      5: 2,
      10: 5
    },
    calligraphy: {
      5: 2,
      10: 5
    },
    courtier: {
      5: 2,
      10: 5
    },
    divination: {
      5: 2,
      10: 5
    },
    etiquette: {
      5: 2,
      10: 5
    },
    games: {
      5: 4,
      10: 7
    },
    instruction: {
      5: 4,
      10: 7
    },
    investigation: {
      5: 2,
      10: 5
    },
    lore: {
      5: 4,
      10: 7
    },
    medicine: {
      5: 2,
      10: 5
    },
    meditation: {
      5: 2,
      7: 2,
      10: 5
    },
    performance: {
      5: 4,
      10: 7
    },
    spellcraft: {
      5: 2,
      10: 5
    },
    storytelling: {
      5: 4,
      10: 7
    },
    tea_ceremony: {
      5: 2,
      10: 5
    },
    theology: {
      5: 4,
      7: 2,
      10: 15
    },
    animal_handling: {
      5: 2,
      10: 5
    },
    commerce: {
      5: 2,
      10: 5
    },
    craft: {
      5: 4,
      10: 7
    },
    engineering: {
      5: 2,
      10: 5
    },
    locksmith: {
      5: 2,
      10: 5
    },
    athletics: {
      5: 2,
      10: 5
    },
    battle: {
      5: 2,
      10: 5
    },
    chain_weapons: {
      5: 2,
      10: 5
    },
    heavy_weapons: {
      5: 2,
      10: 5
    },
    kenjutsu: {
      5: 2,
      10: 5
    },
    knives: {
      5: 2,
      10: 5
    },
    kyujutsu: {
      5: 2,
      10: 5
    },
    ninja_weapons: {
      5: 2,
      10: 5
    },
    peasant_weapons: {
      5: 2,
      10: 5
    },
    polearms: {
      5: 2,
      10: 5
    },
    spears: {
      5: 2,
      10: 5
    },
    staves: {
      5: 2,
      10: 5
    },
    war_fans: {
      5: 2,
      10: 5
    },
    defense: {
      5: 2,
      10: 5
    },
    horsemanship: {
      5: 2,
      10: 5
    },
    hunting: {
      5: 2,
      10: 5
    },
    iaijutsu: {
      5: 2,
      10: 5
    },
    jiujutsu: {
      5: 2,
      10: 5
    },
    know_the_school: {
      5: 2,
      10: 5
    },
    anatomy: {
      5: 2,
      10: 5
    },
    deceit: {
      5: 2,
      10: 5
    },
    explosives: {
      5: 2,
      10: 5
    },
    forgery: {
      5: 2,
      10: 5
    },
    poison: {
      5: 2,
      10: 5
    },
    sleight_of_hand: {
      5: 2,
      10: 5
    },
    stealth: {
      5: 2,
      10: 5
    },
    traps: {
      5: 2,
      10: 5
    },
    underworld: {
      5: 2,
      10: 5
    }
  };

  merge_objects = function() {
    var n, obj, objs, r, v, _i, _len;
    objs = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    r = {};
    for (_i = 0, _len = objs.length; _i < _len; _i++) {
      obj = objs[_i];
      for (n in obj) {
        v = obj[n];
        r[n] = v;
      }
    }
    return r;
  };

  varnamize = function(str) {
    return str.replace(/^\s+|\s+$/g, '').toLowerCase().replace(/[ ']/, '_');
  };

  object_keep = function(obj, list) {
    var i, r, _i, _ref;
    r = {};
    for (i = _i = 0, _ref = list.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
      r[list[i]] = obj[list[i]];
    }
    return r;
  };

  min = Math.min;

  max = Math.max;

  floor = Math.floor;

  ceil = Math.ceil;

  PRIMARY_MAPPING = {
    stamina: {
      where: '#general + div .table:nth-of-type(2) .row0 .col1',
      type: 'int'
    },
    willpower: {
      where: '#general + div .table:nth-of-type(2) .row0 .col3',
      type: 'int'
    },
    strength: {
      where: '#general + div .table:nth-of-type(2) .row1 .col1',
      type: 'int'
    },
    perception: {
      where: '#general + div .table:nth-of-type(2) .row1 .col3',
      type: 'int'
    },
    agility: {
      where: '#general + div .table:nth-of-type(2) .row2 .col1',
      type: 'int'
    },
    intelligence: {
      where: '#general + div .table:nth-of-type(2) .row2 .col3',
      type: 'int'
    },
    reflexes: {
      where: '#general + div .table:nth-of-type(2) .row3 .col1',
      type: 'int'
    },
    awareness: {
      where: '#general + div .table:nth-of-type(2) .row3 .col3',
      type: 'int'
    },
    "void": {
      where: '#general + div .table:nth-of-type(2) .row4 .col1',
      type: 'int'
    },
    status: {
      where: '#general + div .table:nth-of-type(3) .row0 .col1',
      type: 'rank'
    },
    glory: {
      where: '#general + div .table:nth-of-type(3) .row0 .col3',
      type: 'rank'
    },
    honor: {
      where: '#general + div .table:nth-of-type(3) .row0 .col5',
      type: 'rank'
    },
    taint: {
      where: '#general + div .table:nth-of-type(3) .row0 .col7',
      type: 'rank'
    },
    wounds_healthy: {
      where: '#wounds + div .table:nth-of-type(1) .row1 .col2',
      type: 'int'
    },
    wounds_nicked: {
      where: '#wounds + div .table:nth-of-type(1) .row2 .col2',
      type: 'int'
    },
    wounds_grazed: {
      where: '#wounds + div .table:nth-of-type(1) .row3 .col2',
      type: 'int'
    },
    wounds_hurt: {
      where: '#wounds + div .table:nth-of-type(1) .row4 .col2',
      type: 'int'
    },
    wounds_injured: {
      where: '#wounds + div .table:nth-of-type(1) .row5 .col2',
      type: 'int'
    },
    wounds_crippled: {
      where: '#wounds + div .table:nth-of-type(1) .row6 .col2',
      type: 'int'
    },
    wounds_down: {
      where: '#wounds + div .table:nth-of-type(1) .row7 .col2',
      type: 'int'
    },
    wounds_out: {
      where: '#wounds + div .table:nth-of-type(1) .row8 .col2',
      type: 'int'
    },
    skills: {
      where: '#skills + div .table:nth-of-type(1) tr:gt(0)',
      type: function($sel) {
        var elem, _i, _len, _ref, _results;
        _ref = $sel.toArray();
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          elem = _ref[_i];
          _results.push({
            category: varnamize($(elem).find('.col0 a').text()),
            name: $(elem).find('.col0').text(),
            emphases: $(elem).find('.col1').text(),
            rank: Number($(elem).find('.col2').text())
          });
        }
        return _results;
      }
    }
  };

  SECONDARY_MAPPING = {
    earth: {
      where: '#general + div .table:nth-of-type(2) .row0 .col5',
      type: 'int',
      compute: function() {
        return min(this.willpower, this.stamina);
      }
    },
    water: {
      where: '#general + div .table:nth-of-type(2) .row1 .col5',
      type: 'int',
      compute: function() {
        return min(this.perception, this.strength);
      }
    },
    fire: {
      where: '#general + div .table:nth-of-type(2) .row2 .col5',
      type: 'int',
      compute: function() {
        return min(this.intelligence, this.agility);
      }
    },
    air: {
      where: '#general + div .table:nth-of-type(2) .row3 .col5',
      type: 'int',
      compute: function() {
        return min(this.awareness, this.reflexes);
      }
    },
    insight: {
      where: '#general + div .table:nth-of-type(1) .row1 .col1',
      type: 'int',
      compute: function() {
        var from_mastery, from_rings, from_skills, insight_bonus_level, skill, _i, _j, _len, _len1, _ref, _ref1;
        from_rings = (this.earth + this.water + this.air + this.fire + this["void"]) * 10;
        from_skills = 0;
        from_mastery = 0;
        _ref = this.skills;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          skill = _ref[_i];
          from_skills += skill.rank;
          _ref1 = SKILLS[skill.category];
          for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
            insight_bonus_level = _ref1[_j];
            if (skill.rank >= insight_bonus_level) {
              from_mastery += SKILLS[skill.category][insight_bonus_level];
            }
          }
        }
        return from_rings + from_skills + from_mastery;
      }
    },
    insight_rank: {
      where: '#general + div .table:nth-of-type(1) .row1 .col3',
      type: 'int',
      compute: function() {
        return max(1, floor((this.insight - 150) / 25) + 2);
      }
    },
    wounds_healthy_max: {
      where: '#wounds + div .table:nth-of-type(1) .row1 .col1',
      type: 'int',
      compute: function() {
        return this.earth * 2;
      }
    },
    wounds_nicked_max: {
      where: '#wounds + div .table:nth-of-type(1) .row2 .col1',
      type: 'int',
      compute: function() {
        return this.earth * 2;
      }
    },
    wounds_grazed_max: {
      where: '#wounds + div .table:nth-of-type(1) .row3 .col1',
      type: 'int',
      compute: function() {
        return this.earth * 2;
      }
    },
    wounds_hurt_max: {
      where: '#wounds + div .table:nth-of-type(1) .row4 .col1',
      type: 'int',
      compute: function() {
        return this.earth * 2;
      }
    },
    wounds_injured_max: {
      where: '#wounds + div .table:nth-of-type(1) .row5 .col1',
      type: 'int',
      compute: function() {
        return this.earth * 2;
      }
    },
    wounds_crippled_max: {
      where: '#wounds + div .table:nth-of-type(1) .row6 .col1',
      type: 'int',
      compute: function() {
        return this.earth * 2;
      }
    },
    wounds_down_max: {
      where: '#wounds + div .table:nth-of-type(1) .row7 .col1',
      type: 'int',
      compute: function() {
        return this.earth * 2;
      }
    },
    wounds_out_max: {
      where: '#wounds + div .table:nth-of-type(1) .row8 .col1',
      type: 'int',
      compute: function() {
        return this.earth * 5;
      }
    }
  };

  SHEET_MAPPING = merge_objects(PRIMARY_MAPPING, SECONDARY_MAPPING);

  CharacterSheet = (function() {
    function CharacterSheet(mapping) {
      var attr_name, properties, _ref;
      this.mapping = mapping;
      _ref = this.mapping;
      for (attr_name in _ref) {
        properties = _ref[attr_name];
        this[attr_name] = $(properties.where);
      }
    }

    CharacterSheet.prototype.set = function(attr, val) {
      var attr_name, value, _results;
      if (typeof attr === 'string') {
        switch (this.mapping[attr].type) {
          case 'int':
            return this[attr].text(val);
          case 'rank':
            return this[attr].text(val.join('.'));
        }
      } else {
        _results = [];
        for (attr_name in attr) {
          value = attr[attr_name];
          _results.push(this.set(attr_name, value));
        }
        return _results;
      }
    };

    CharacterSheet.prototype.get = function(attr) {
      var attr_name, result, value;
      if (typeof attr === 'string') {
        if (typeof this.mapping[attr].type === 'function') {
          return this.mapping[attr].type(this[attr]);
        } else {
          switch (this.mapping[attr].type) {
            case 'int':
              return Number(this[attr].text());
            case 'rank':
              return this[attr].text().split('.').map(Number);
          }
        }
      } else {
        result = {};
        for (attr_name in attr) {
          value = attr[attr_name];
          result[attr_name] = this.get(attr_name);
        }
        return result;
      }
    };

    CharacterSheet.prototype.regroup_effects = function(where) {
      var $where, domain, domain_effects, effect_attr, effect_str, effects, _results;
      $where = $(where).find('ul');
      effects = this.get_all_effects();
      _results = [];
      for (domain in effects) {
        domain_effects = effects[domain];
        _results.push((function() {
          var _i, _len, _results1;
          _results1 = [];
          for (_i = 0, _len = domain_effects.length; _i < _len; _i++) {
            effect_attr = domain_effects[_i];
            effect_str = this.format_effect(effect_attr.effect);
            _results1.push($where.append(("<li class='level1' title='" + effect_attr.because + "'>") + ("<div class='li'><strong>" + domain + "</strong>: " + effect_str + "</div></li>")));
          }
          return _results1;
        }).call(this));
      }
      return _results;
    };

    CharacterSheet.prototype.get_all_effects = function() {
      var effects_record;
      effects_record = {};
      $('.effects > *').each(function() {
        var because, effect, tag;
        tag = this.tagName.toLowerCase();
        because = $(this).attr('because');
        effect = $(this).text();
        if (!effects_record[tag]) {
          effects_record[tag] = [];
        }
        return effects_record[tag].push({
          because: because,
          effect: effect
        });
      });
      return effects_record;
    };

    CharacterSheet.prototype.format_effect = function(str) {
      var err;
      str = str.replace(/^\s+|\s+$/g, '');
      str = '"' + str.replace('#{', '"+(').replace('}', ')+"') + '"';
      str = str.replace('$', 'char.');
      try {
        str = eval(str);
      } catch (_error) {
        err = _error;
        str = err;
      }
      return str;
    };

    CharacterSheet.prototype.complete = function(secondaries) {
      var map, n, name, properties, _results;
      map = {};
      for (n in PRIMARY_MAPPING) {
        map[n] = this.get(n);
      }
      _results = [];
      for (name in secondaries) {
        properties = secondaries[name];
        map[name] = properties.compute.call(map);
        _results.push(this.set(name, map[name]));
      }
      return _results;
    };

    return CharacterSheet;

  })();

  $(function() {
    var sheet;
    sheet = new CharacterSheet(SHEET_MAPPING);
    sheet.complete(SECONDARY_MAPPING);
    return sheet.regroup_effects('#fast_reference + div');
  });

}).call(this);

/*
//@ sourceMappingURL=character_sheet.map
*/
