// Generated by CoffeeScript 1.6.3
(function() {
  var Character, CharacterSheet, PRIMARY_MAPPING, SECONDARY_MAPPING, SHEET_MAPPING, SKILLS, char, merge_objects, object_keep, sheet, varnamize,
    __slice = [].slice;

  SKILLS = {
    acting: {
      5: 2,
      10: 5
    },
    artisan: {
      5: 2,
      10: 5
    },
    calligraphy: {
      5: 2,
      10: 5
    },
    courtier: {
      5: 2,
      10: 5
    },
    divination: {
      5: 2,
      10: 5
    },
    etiquette: {
      5: 2,
      10: 5
    },
    games: {
      5: 4,
      10: 7
    },
    instruction: {
      5: 4,
      10: 7
    },
    investigation: {
      5: 2,
      10: 5
    },
    lore: {
      5: 4,
      10: 7
    },
    medicine: {
      5: 2,
      10: 5
    },
    meditation: {
      5: 2,
      7: 2,
      10: 5
    },
    performance: {
      5: 4,
      10: 7
    },
    spellcraft: {
      5: 2,
      10: 5
    },
    storytelling: {
      5: 4,
      10: 7
    },
    tea_ceremony: {
      5: 2,
      10: 5
    },
    theology: {
      5: 4,
      7: 2,
      10: 15
    },
    animal_handling: {
      5: 2,
      10: 5
    },
    commerce: {
      5: 2,
      10: 5
    },
    craft: {
      5: 4,
      10: 7
    },
    engineering: {
      5: 2,
      10: 5
    },
    locksmith: {
      5: 2,
      10: 5
    },
    athletics: {
      5: 2,
      10: 5
    },
    battle: {
      5: 2,
      10: 5
    },
    chain_weapons: {
      5: 2,
      10: 5
    },
    heavy_weapons: {
      5: 2,
      10: 5
    },
    kenjutsu: {
      5: 2,
      10: 5
    },
    knives: {
      5: 2,
      10: 5
    },
    kyujutsu: {
      5: 2,
      10: 5
    },
    ninja_weapons: {
      5: 2,
      10: 5
    },
    peasant_weapons: {
      5: 2,
      10: 5
    },
    polearms: {
      5: 2,
      10: 5
    },
    spears: {
      5: 2,
      10: 5
    },
    staves: {
      5: 2,
      10: 5
    },
    war_fans: {
      5: 2,
      10: 5
    },
    defense: {
      5: 2,
      10: 5
    },
    horsemanship: {
      5: 2,
      10: 5
    },
    hunting: {
      5: 2,
      10: 5
    },
    iaijutsu: {
      5: 2,
      10: 5
    },
    jiujutsu: {
      5: 2,
      10: 5
    },
    know_the_school: {
      5: 2,
      10: 5
    },
    anatomy: {
      5: 2,
      10: 5
    },
    deceit: {
      5: 2,
      10: 5
    },
    explosives: {
      5: 2,
      10: 5
    },
    forgery: {
      5: 2,
      10: 5
    },
    poison: {
      5: 2,
      10: 5
    },
    sleight_of_hand: {
      5: 2,
      10: 5
    },
    stealth: {
      5: 2,
      10: 5
    },
    traps: {
      5: 2,
      10: 5
    },
    underworld: {
      5: 2,
      10: 5
    }
  };

  merge_objects = function() {
    var n, obj, objs, r, v, _i, _len;
    objs = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    r = {};
    for (_i = 0, _len = objs.length; _i < _len; _i++) {
      obj = objs[_i];
      for (n in obj) {
        v = obj[n];
        r[n] = v;
      }
    }
    return r;
  };

  varnamize = function(str) {
    return str.replace(/^\s+|\s+$/g, '').toLowerCase().replace(/[ ']/, '_');
  };

  object_keep = function(obj, list) {
    var i, r, _i, _ref;
    r = {};
    for (i = _i = 0, _ref = list.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
      r[list[i]] = obj[list[i]];
    }
    return r;
  };

  Character = (function() {
    function Character(attributes) {
      var attribute, value;
      for (attribute in attributes) {
        value = attributes[attribute];
        this[attribute] = value;
      }
      this.earth = this.earth();
      this.fire = this.fire();
      this.water = this.water();
      this.air = this.air();
      this.insight = this.insight();
      this.insight_rank = this.insight_rank();
      this.wounds_healthy_max = this.wounds_healthy_max();
      this.wounds_nicked_max = this.wounds_nicked_max();
      this.wounds_grazed_max = this.wounds_grazed_max();
      this.wounds_hurt_max = this.wounds_hurt_max();
      this.wounds_injured_max = this.wounds_injured_max();
      this.wounds_crippled_max = this.wounds_crippled_max();
      this.wounds_down_max = this.wounds_down_max();
      this.wounds_out_max = this.wounds_out_max();
    }

    Character.prototype.earth = function() {
      return Math.min(this.stamina, this.willpower);
    };

    Character.prototype.fire = function() {
      return Math.min(this.agility, this.intelligence);
    };

    Character.prototype.water = function() {
      return Math.min(this.strength, this.perception);
    };

    Character.prototype.air = function() {
      return Math.min(this.reflexes, this.awareness);
    };

    Character.prototype.insight = function() {
      var from_mastery, from_rings, from_skills, insight_bonus_level, name, skill, val, _i, _j, _len, _len1, _ref, _ref1;
      from_rings = (this.earth + this.water + this.air + this.fire + this["void"]) * 10;
      from_skills = 0;
      from_mastery = 0;
      _ref = this.skills;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        skill = _ref[_i];
        name = skill[0], val = skill[1];
        from_skills += val;
        _ref1 = SKILLS[name];
        for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
          insight_bonus_level = _ref1[_j];
          if (val >= insight_bonus_level) {
            from_mastery += SKILLS[name][insight_bonus_level];
          }
        }
      }
      return from_rings + from_skills + from_mastery;
    };

    Character.prototype.wounds_healthy_max = function() {
      return this.earth * 2;
    };

    Character.prototype.wounds_nicked_max = function() {
      return this.earth * 2;
    };

    Character.prototype.wounds_grazed_max = function() {
      return this.earth * 2;
    };

    Character.prototype.wounds_hurt_max = function() {
      return this.earth * 2;
    };

    Character.prototype.wounds_injured_max = function() {
      return this.earth * 2;
    };

    Character.prototype.wounds_crippled_max = function() {
      return this.earth * 2;
    };

    Character.prototype.wounds_down_max = function() {
      return this.earth * 2;
    };

    Character.prototype.wounds_out_max = function() {
      return this.earth * 5;
    };

    Character.prototype.insight_rank = function() {
      return Math.max(1, Math.floor((this.insight - 150) / 25) + 2);
    };

    return Character;

  })();

  Character.from_sheet = function(sheet) {
    return new Character(sheet.get(PRIMARY_MAPPING));
  };

  PRIMARY_MAPPING = {
    stamina: {
      where: '#general + div .table:nth-of-type(2) .row0 .col1',
      type: 'int'
    },
    willpower: {
      where: '#general + div .table:nth-of-type(2) .row0 .col3',
      type: 'int'
    },
    strength: {
      where: '#general + div .table:nth-of-type(2) .row1 .col1',
      type: 'int'
    },
    perception: {
      where: '#general + div .table:nth-of-type(2) .row1 .col3',
      type: 'int'
    },
    agility: {
      where: '#general + div .table:nth-of-type(2) .row2 .col1',
      type: 'int'
    },
    intelligence: {
      where: '#general + div .table:nth-of-type(2) .row2 .col3',
      type: 'int'
    },
    reflexes: {
      where: '#general + div .table:nth-of-type(2) .row3 .col1',
      type: 'int'
    },
    awareness: {
      where: '#general + div .table:nth-of-type(2) .row3 .col3',
      type: 'int'
    },
    "void": {
      where: '#general + div .table:nth-of-type(2) .row4 .col1',
      type: 'int'
    },
    status: {
      where: '#general + div .table:nth-of-type(3) .row0 .col1',
      type: 'rank'
    },
    glory: {
      where: '#general + div .table:nth-of-type(3) .row0 .col3',
      type: 'rank'
    },
    honor: {
      where: '#general + div .table:nth-of-type(3) .row0 .col5',
      type: 'rank'
    },
    taint: {
      where: '#general + div .table:nth-of-type(3) .row0 .col7',
      type: 'rank'
    },
    wounds_healthy: {
      where: '#wounds + div .table:nth-of-type(1) .row1 .col2',
      type: 'int'
    },
    wounds_nicked: {
      where: '#wounds + div .table:nth-of-type(1) .row2 .col2',
      type: 'int'
    },
    wounds_grazed: {
      where: '#wounds + div .table:nth-of-type(1) .row3 .col2',
      type: 'int'
    },
    wounds_hurt: {
      where: '#wounds + div .table:nth-of-type(1) .row4 .col2',
      type: 'int'
    },
    wounds_injured: {
      where: '#wounds + div .table:nth-of-type(1) .row5 .col2',
      type: 'int'
    },
    wounds_crippled: {
      where: '#wounds + div .table:nth-of-type(1) .row6 .col2',
      type: 'int'
    },
    wounds_down: {
      where: '#wounds + div .table:nth-of-type(1) .row7 .col2',
      type: 'int'
    },
    wounds_out: {
      where: '#wounds + div .table:nth-of-type(1) .row8 .col2',
      type: 'int'
    },
    skills: {
      where: '#skills + div .table:nth-of-type(1) tr:gt(0)',
      type: function($sel) {
        var result;
        result = [];
        $sel.each(function() {
          var name, val;
          name = varnamize($(this).find('.col0 a').text());
          val = Number($(this).find('.col2').text());
          return result.push([name, val]);
        });
        return result;
      }
    }
  };

  SECONDARY_MAPPING = {
    earth: {
      where: '#general + div .table:nth-of-type(2) .row0 .col5',
      type: 'int'
    },
    water: {
      where: '#general + div .table:nth-of-type(2) .row1 .col5',
      type: 'int'
    },
    fire: {
      where: '#general + div .table:nth-of-type(2) .row2 .col5',
      type: 'int'
    },
    air: {
      where: '#general + div .table:nth-of-type(2) .row3 .col5',
      type: 'int'
    },
    insight: {
      where: '#general + div .table:nth-of-type(1) .row1 .col1',
      type: 'int'
    },
    insight_rank: {
      where: '#general + div .table:nth-of-type(1) .row1 .col3',
      type: 'int'
    },
    wounds_healthy_max: {
      where: '#wounds + div .table:nth-of-type(1) .row1 .col1',
      type: 'int'
    },
    wounds_nicked_max: {
      where: '#wounds + div .table:nth-of-type(1) .row2 .col1',
      type: 'int'
    },
    wounds_grazed_max: {
      where: '#wounds + div .table:nth-of-type(1) .row3 .col1',
      type: 'int'
    },
    wounds_hurt_max: {
      where: '#wounds + div .table:nth-of-type(1) .row4 .col1',
      type: 'int'
    },
    wounds_injured_max: {
      where: '#wounds + div .table:nth-of-type(1) .row5 .col1',
      type: 'int'
    },
    wounds_crippled_max: {
      where: '#wounds + div .table:nth-of-type(1) .row6 .col1',
      type: 'int'
    },
    wounds_down_max: {
      where: '#wounds + div .table:nth-of-type(1) .row7 .col1',
      type: 'int'
    },
    wounds_out_max: {
      where: '#wounds + div .table:nth-of-type(1) .row8 .col1',
      type: 'int'
    }
  };

  SHEET_MAPPING = merge_objects(PRIMARY_MAPPING, SECONDARY_MAPPING);

  sheet = {};

  char = {};

  CharacterSheet = (function() {
    function CharacterSheet(mapping) {
      var attr_name, properties, _ref;
      this.mapping = mapping;
      _ref = this.mapping;
      for (attr_name in _ref) {
        properties = _ref[attr_name];
        this[attr_name] = $(properties.where);
      }
    }

    CharacterSheet.prototype.set = function(attr, val) {
      var attr_name, value, _results;
      if (typeof attr === 'string') {
        switch (this.mapping[attr].type) {
          case 'int':
            return this[attr].text(val);
          case 'rank':
            return this[attr].text(val.join('.'));
        }
      } else {
        _results = [];
        for (attr_name in attr) {
          value = attr[attr_name];
          _results.push(this.set(attr_name, value));
        }
        return _results;
      }
    };

    CharacterSheet.prototype.get = function(attr) {
      var attr_name, result, value;
      if (typeof attr === 'string') {
        if (typeof this.mapping[attr].type === 'function') {
          return this.mapping[attr].type(this[attr]);
        } else {
          switch (this.mapping[attr].type) {
            case 'int':
              return Number(this[attr].text());
            case 'rank':
              return this[attr].text().split('.').map(Number);
          }
        }
      } else {
        result = {};
        for (attr_name in attr) {
          value = attr[attr_name];
          result[attr_name] = this.get(attr_name);
        }
        return result;
      }
    };

    CharacterSheet.prototype.regroup_effects = function(where) {
      var $where, domain, domain_effects, effect_attr, effect_str, effects, _results;
      $where = $(where).find('ul');
      effects = this.get_all_effects();
      _results = [];
      for (domain in effects) {
        domain_effects = effects[domain];
        _results.push((function() {
          var _i, _len, _results1;
          _results1 = [];
          for (_i = 0, _len = domain_effects.length; _i < _len; _i++) {
            effect_attr = domain_effects[_i];
            effect_str = this.format_effect(effect_attr.effect);
            _results1.push($where.append(("<li class='level1' title='" + effect_attr.because + "'>") + ("<div class='li'><strong>" + domain + "</strong>: " + effect_str + "</div></li>")));
          }
          return _results1;
        }).call(this));
      }
      return _results;
    };

    CharacterSheet.prototype.get_all_effects = function() {
      var effects_record;
      effects_record = {};
      $('.effects > *').each(function() {
        var because, effect, tag;
        tag = this.tagName.toLowerCase();
        because = $(this).attr('because');
        effect = $(this).text();
        if (!effects_record[tag]) {
          effects_record[tag] = [];
        }
        return effects_record[tag].push({
          because: because,
          effect: effect
        });
      });
      return effects_record;
    };

    CharacterSheet.prototype.format_effect = function(str) {
      var err;
      str = str.replace(/^\s+|\s+$/g, '');
      str = '"' + str.replace('#{', '"+(').replace('}', ')+"') + '"';
      str = str.replace('$', 'char.');
      try {
        str = eval(str);
      } catch (_error) {
        err = _error;
        str = err;
      }
      return str;
    };

    return CharacterSheet;

  })();

  $(function() {
    sheet = new CharacterSheet(SHEET_MAPPING);
    char = Character.from_sheet(sheet);
    sheet.set(char);
    return sheet.regroup_effects('#fast_reference + div');
  });

}).call(this);

/*
//@ sourceMappingURL=character_sheet.map
*/
