// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    var shuffle;
    return shuffle = function(array) {
      var currentIndex, randomIndex, temporaryValue;
      currentIndex = array.length;
      while (0 !== currentIndex) {
        randomIndex = Math.floor(Math.random() * currentIndex);
        currentIndex -= 1;
        temporaryValue = array[currentIndex];
        array[currentIndex] = array[randomIndex];
        array[randomIndex] = temporaryValue;
      }
      return array.filter(function(e) {
        return e != null;
      });
    };
  });

  $(function() {
    var exploding_d10_roll, fair_d10_roll;
    $('#roll-spinner, #keep-spinner').spinner({
      max: 10,
      min: 1
    }).spinner('value', 1);
    $('#roll-button').click(function() {
      var $row, dont_sort, explode, final_result, i, loose_biggest, results, roll_method, rolls, to_keep, to_roll;
      to_roll = $('#roll-spinner').spinner('value');
      to_keep = $('#keep-spinner').spinner('value');
      explode = $('#explode-checkbox').prop('checked');
      dont_sort = $('#dont-sort-checkbox').prop('checked');
      loose_biggest = $('#loose-biggest-checkbox').prop('checked');
      roll_method = explode ? exploding_d10_roll : fair_d10_roll;
      rolls = (function() {
        var _i, _results;
        _results = [];
        for (i = _i = 0; 0 <= to_roll ? _i < to_roll : _i > to_roll; i = 0 <= to_roll ? ++_i : --_i) {
          _results.push(roll_method());
        }
        return _results;
      })();
      results = (function() {
        var _i, _results;
        _results = [];
        for (i = _i = 0; _i < 10; i = ++_i) {
          _results.push(rolls[i]);
        }
        return _results;
      })();
      results = results.sort(function(a, b) {
        return a < b;
      }).map(function(e, i) {
        return {
          keep: i < to_keep,
          result: e
        };
      });
      if (loose_biggest) {
        results.forEach(function(e, i) {
          return e.keep = 0 < i && i < to_keep + 1;
        });
      }
      if (dont_sort) {
        results = shuffle(results);
        results.forEach(function(e, i) {
          return e.keep = false;
        });
      }
      final_result = results.map(function(p) {
        if (p.keep) {
          return p.result;
        } else {
          return 0;
        }
      }).reduce((function(p, c) {
        return c + p;
      }), 0);
      $row = $('<tr></tr>').prependTo('#result');
      $(results).each(function(i, e) {
        if (e.result != null) {
          return $("<td>" + e.result + "</td>").toggleClass('keep', e.keep).appendTo($row);
        } else {
          return $('<td class="empty"></td>').appendTo($row);
        }
      });
      return $("<td class='sum'>" + final_result + "</td>").appendTo($row);
    });
    exploding_d10_roll = function(threshold) {
      var r, re_roll, result;
      if (threshold == null) {
        threshold = 10;
      }
      re_roll = true;
      result = 0;
      while (re_roll) {
        r = fair_d10_roll();
        result += r;
        re_roll = r >= threshold;
      }
      return result;
    };
    return fair_d10_roll = function() {
      return Math.floor(Math.random() * 10) + 1;
    };
  });

}).call(this);

/*
//@ sourceMappingURL=dices.map
*/
