// Generated by CoffeeScript 1.6.3
(function() {
  beforeEach(function() {
    return jasmine.addMatchers({
      toBePlaying: function() {
        return {
          compare: function(actual, expected) {
            var player;
            player = actual;
            return {
              pass: player.currentlyPlayingSong === expected && player.isPlaying
            };
          }
        };
      }
    });
  });

}).call(this);
